version: '2'
services:

 mitmproxy:
  image: marcelmaatkamp/mitmproxy-mitm-scripts:latest
  build: .
  stdin_open: true
  tty: true
  command: ash -c 'mitmweb --no-http2 --web-iface 0.0.0.0 --set console_eventlog_verbosity=debug --set termlog_verbosity=info -s mitm-redirect-host.py'
  ports: 
   - 8080:8080
   - 8081:8081
  volumes:
   - ./etc/mitm-scripts/redirect-router.yaml:/home/mitmproxy/mitm-scripts/redirect-router.yaml
   - ./etc/mitm-scripts/.mitmproxy:/home/mitmproxy/.mitmproxy

 nginx:
  image: nginx:1.17.8
  volumes:
   - ./etc/nginx/html:/usr/share/nginx/html
   - ./etc/nginx/conf.d:/etc/nginx/conf.d
