version: '2'
services:

 mitmproxy:
  image: marcelmaatkamp/mitmproxy-mitm-scripts:latest
  build: .
  stdin_open: true
  tty: true
  command: ash -c 'mitmweb --web-iface 0.0.0.0 --set termlog_verbosity=warn -s mitm-redirect-host.py'
  ports: 
   - 8080:8080
   - 8081:8081
  volumes:
   - ./etc/mitm-scripts/redirect-router.yaml:/home/mitmproxy/mitm-scripts/redirect-router.yaml

 nginx:
  image: nginx:1.17.8
  volumes:
   - ./etc/nginx:/usr/share/nginx/html
